import { getStore } from '@netlify/blobs';
const STORE='hikari-portal', KEY='projects-v2';
const reply=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(v,n=120)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,n);
const id=()=>`${Date.now().toString(36)}_${crypto.randomUUID().replaceAll('-','')}`;
async function read(s){return (await s.get(KEY,{type:'json'}))||[]}
async function write(s,x){await s.setJSON(KEY,x.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.shipNo.localeCompare(b.shipNo,'ja')))}
function validate(x){const v={shipNo:clean(x.shipNo,60),displayName:clean(x.displayName,80),productName:clean(x.productName,120),client:clean(x.client,100),employeeId:clean(x.employeeId,100),dueDate:clean(x.dueDate,10),notes:clean(x.notes,500),quantity:Math.max(0,Number(x.quantity)||0),spec:clean(x.spec,300),completed:Boolean(x.completed)};if(!v.displayName||!v.productName||!v.employeeId||!/^\d{4}-\d{2}-\d{2}$/.test(v.dueDate))return {error:'表示名・製品名・担当者・納期を入力してください。'};return v}
export default async req=>{const s=getStore({name:STORE,consistency:'strong'}),u=new URL(req.url);try{let items=await read(s);if(req.method==='GET')return reply({projects:items});if(req.method==='POST'){const x=await req.json();if(Array.isArray(x.projects)){if(!x.projects.length||x.projects.length>200)return reply({error:'一度に登録できる明細は1〜200件です。'},400);const now=new Date().toISOString(),created=[];for(const raw of x.projects){const v=validate(raw);if(v.error)return reply(v,400);created.push({id:id(),...v,createdAt:now,updatedAt:now})}items.push(...created);await write(s,items);return reply({projects:created},201)}const v=validate(x);if(v.error)return reply(v,400);const now=new Date().toISOString(),p={id:id(),...v,createdAt:now,updatedAt:now};items.push(p);await write(s,items);return reply({project:p},201)}if(req.method==='PUT'){const x=await req.json(),i=items.findIndex(p=>p.id===x.id);if(i<0)return reply({error:'案件が見つかりません。'},404);if(x.action==='toggle')items[i]={...items[i],completed:!items[i].completed,updatedAt:new Date().toISOString()};else{const v=validate(x);if(v.error)return reply(v,400);items[i]={...items[i],...v,updatedAt:new Date().toISOString()}}await write(s,items);return reply({project:items[i]})}if(req.method==='DELETE'){let ids=[];const q=u.searchParams.get('id');if(q)ids=[q];else{let body={};try{body=await req.json()}catch{}ids=Array.isArray(body.ids)?body.ids.map(x=>clean(x,100)).filter(Boolean):[]}if(!ids.length||ids.length>200)return reply({error:'削除する案件を1〜200件で指定してください。'},400);const set=new Set(ids),n=items.filter(p=>!set.has(p.id)),deleted=items.length-n.length;if(!deleted)return reply({error:'案件が見つかりません。'},404);await write(s,n);return reply({ok:true,deleted})}return reply({error:'対応していない操作です。'},405)}catch(e){console.error(e);return reply({error:'案件データを処理できませんでした。'},500)}};
export const config={path:'/api/projects'};
